# Generated by Django 5.1.5 on 2026-02-24 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigMode",
            fields=[
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("hard", "Hard"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reward_points", models.IntegerField()),
                ("penalty_points", models.IntegerField()),
                ("time_limit_seconds", models.IntegerField(blank=True, null=True)),
                ("signal_intel_level", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="daily_cycle",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="elapsed_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="session_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rank",
            field=models.CharField(
                blank=True, default="Initiate", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guestuse", "Guest"),
                    ("loguse", "Registered"),
                    ("paiduse", "Paid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="mode_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="hardle.configmode",
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=5)),
                ("active_date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["active_date"], name="idx_words_active_date")
                ],
            },
        ),
        migrations.AddField(
            model_name="gamesession",
            name="word_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="hardle.word",
            ),
        ),
    ]
